# Generated by Django 4.2.9 on 2024-12-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customeridentity_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeridentity',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
