# Generated by Django 4.2.9 on 2024-12-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
    ]
